export const categoriesTypesArray = [
  "Food & Dining",
  "Groceries",
  "Restaurants",
  "Transport",
  "Fuel",
  "Public Transport",
  "Shopping",
  "Clothing",
  "Electronics",
  "Entertainment",
  "Movies",
  "Games",
  "Health & Fitness",
  "Gym",
  "Medicine",
  "Doctor",
  "Bills & Utilities",
  "Electricity",
  "Water",
  "Internet",
  "Rent",
  "Education",
  "Tuition",
  "Books",
  "Insurance",
  "Car Insurance",
  "Health Insurance",
  "Home Insurance",
  "Travel",
  "Flight",
  "Hotel",
  "Other",
  "Gifts",
  "Donations",
  "Investments",
  "Savings",
  "Miscellaneous",
];
